language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - nightly

install:
  - composer install --no-interaction

notifications:
  email: false

allow_failures:
    - php: nightly