language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - nightly

install:
  - composer install --no-interaction
  - composer cs-check
  - composer license-check
  - composer phpstan
  - composer phpunit-coverage

notifications:
  email: false

allow_failures:
    - php: nightly