language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2

install:
  - composer install --no-interaction
  - composer cs-check
  - composer license-check
  - composer phpstan
  - composer phpunit-coverage

after_script:
  - php ./vendor/bin/coveralls -v

notifications:
  email: false

allow_failures:
    - php: nightly